# How to use it?
# docker compose -f docker-compose-prod.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/grammar-rush
  grammar-rush-spring:
    build:
      context: ./grammar-rush-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: postgres
      ADMIN_NAME: admin
      ADMIN_PASSWORD: password
      POSTGRES_URL: jdbc:postgresql://grammar-rush-db:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DDL_AUTO: update
    depends_on:
      - grammar-rush-db
      - grammar-rush-pgadmin
    networks:
      - grammar-rush

  grammar-rush-react:
    build:
      context: .
      dockerfile: ./docker/static-server/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=http://api.grammar-rush.ru
    networks:
     - grammar-rush

  grammar-rush-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - grammar-rush-db:/data/postgres
    networks:
      - grammar-rush
    restart: unless-stopped

  grammar-rush-pgadmin:
    container_name: grammar-rush-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - grammar-rush-pgadmin:/var/lib/pgadmin
    depends_on:
      - grammar-rush-db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - grammar-rush
    restart: unless-stopped

networks:
  grammar-rush:
    driver: bridge

volumes:
  grammar-rush-db:
  grammar-rush-pgadmin: