# How to use it?
# docker compose -f docker-compose-prod.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/yeap-english
  yeap-english-spring:
    build:
      context: ./yeap-english-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: postgres
      ADMIN_NAME: admin
      ADMIN_PASSWORD: password
      POSTGRES_URL: jdbc:postgresql://yeap-english-db:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DDL_AUTO: update
    depends_on:
      - yeap-english-db
      - yeap-english-pgadmin
    networks:
      - yeap-english

  yeap-english-react:
    build:
      context: .
      dockerfile: ./docker/static-server/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=http://api.yeap-english.ru
    networks:
     - yeap-english

  yeap-english-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - yeap-english-db:/data/postgres
    networks:
      - yeap-english
    restart: unless-stopped

  yeap-english-pgadmin:
    container_name: yeap-english-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - yeap-english-pgadmin:/var/lib/pgadmin
    depends_on:
      - yeap-english-db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - yeap-english
    restart: unless-stopped

networks:
  yeap-english:
    driver: bridge

volumes:
  yeap-english-db:
  yeap-english-pgadmin: