# How to use it?
# docker compose -f docker-compose-prod.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/yeap-english
  yeap-english-spring:
    build:
      context: ./yeap-english-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: ${PROFILE_ACTIVE:-postgres}
      ADMIN_NAME: ${ADMIN_NAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      POSTGRES_URL: jdbc:postgresql://yeap-english-db:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ALLOWED_ORIGINS_ARRAY: ${ALLOWED_ORIGINS_ARRAY:-http://localhost:3000}
      POSTGRES_DDL_AUTO: update
    depends_on:
      - yeap-english-db
    networks:
      - nginx-proxy-manager_default

  yeap-english-react:
    build:
      context: .
      dockerfile: ./docker/static-server/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    networks:
     - nginx-proxy-manager_default

  yeap-english-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - yeap-english-db:/data/postgres
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true

volumes:
  yeap-english-db: